version: "3.8"
networks:
  default:
    name: currency
services:
  currency-db-test:
    hostname: "currency-db-test"
    image: currency-db:0.0.1
    container_name: currency-db-test
    ports:
      - "25432:5432"
    env_file:
      - ../data-fetcher/env/db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --host=localhost --username=${TEST_DB_USER} --dbname=${TEST_DB_NAME}"]
      interval: 1s
      retries: 3
      timeout: 5s
  migrations:
    image: go-migration:0.0.1
    depends_on:
      currency-db-test:
        condition: service_healthy
    container_name: migrations
    env_file:
      - ../data-fetcher/env/db.env
    volumes:
      - ../data-fetcher/migrations:/migrations/migrations
    entrypoint: /migrations/migrate -path=/migrations/migrations -database "postgres://${TEST_DB_USER}:${TEST_DB_PASSWORD}@${TEST_DB_HOST}:${TEST_DB_PORT}/${TEST_DB_NAME}?sslmode=disable" up